### ISSUE TITLE
Error compiling with Grails 2.5.0 (Groovy 2.4.3)

### ISSUE THREAD

**Issue by rmondejar** [plexiti/camunda-grails-plugin#44]
Creating a clean project (Grails 2.5.0) and only adding the camunda plugin, it cannot run the app, bcause the new compiler (groovy 2.4.3) didn't allow to have static and non static methods with the same signature, concretely in the class : src/groovy/grails/plugin/camunda/Configuration.groovy

Stacktrace (2 errors) : 

| Compiling 125 source files.
| Error Compilation error: startup failed:
/test-camunda/target/work/plugins/camunda-0.4.0/src/groovy/grails/plugin/camunda/Configuration.groovy: 193: Method 'getProperty' is already defined in class 'grails.plugin.camunda.Configuration'. You cannot have both a static and a non static method with the same signature
 @ line 193, column 3.
     static Object getProperty(String property) {
     ^
/test-camunda/target/work/plugins/camunda-0.4.0/src/groovy/grails/plugin/camunda/Configuration.groovy: 200: Method 'setProperty' is already defined in class 'grails.plugin.camunda.Configuration'. You cannot have both a static and a non static method with the same signature
 @ line 200, column 3.
     static void setProperty(String property, Object value) {
     ^

**Comment by martinschimak** [comment]
Thanks for reporting. Will look into that asap.

**Comment by YaShino** [comment]
I have the same errors when i added only the camunda plugin -- grails(2.4.4) GrrovyCompiler(2.3).

**Comment by richardgear** [comment]
Hi Martin,

Notice that you have closed this ticket, is the fix available for the grails plugin? Thanks.
