### ISSUE TITLE
How to disable the job executor?

### ISSUE THREAD

**Issue by jeffyung** [plexiti/camunda-grails-plugin#46]
I would like to disable the job execution in our application server (tomcat). 
So what we did is to set jobExecutorActivate to false in Config.groovy: 

camunda { 
        engine { 
                deployment.scenario = "embedded" 
                configuration { 
                        databaseType = "postgres" 
                        dataSource = new RuntimeBeanReference("dataSource_camunda") 
                        databaseSchemaUpdate = false 
                        jobExecutorActivate = false 
                        deploymentResources = ['....']                         
                        history = "full" 
                } 
        } 

However, when we start the tomcat, I can still see the start up messages like this: 

Apr 24, 2015 4:02:18 PM org.camunda.bpm.engine.impl.jobexecutor.JobExecutor start 
INFO: Starting up the JobExecutor[org.camunda.bpm.engine.impl.jobexecutor.RuntimeContainerJobExecutor]. 
Apr 24, 2015 4:02:18 PM org.camunda.bpm.engine.impl.jobexecutor.SequentialJobAcquisitionRunnable run 
INFO: JobExecutor[org.camunda.bpm.engine.impl.jobexecutor.RuntimeContainerJobExecutor] starting to acquire jobs 
Apr 24, 2015 4:06:33 PM org.camunda.bpm.engine.impl.ProcessEngineImpl <init> 
INFO: ProcessEngine default created 

The result is it will still execute the jobs. 
May I know if there is anything missed in my configuration or there is other proper way to handle this so that the job executor can be stopped. 

Thanks!
Jeff

**Comment by martinschimak** [comment]
I cannot reproduce this. When configuring the jobExecutor like shown above, it won't acquire jobs anymore. Please make sure that you configure the correct environment and the correct ProcessEngine. With the Config.groovy you configure the embedded process engine. In case you use a camunda BPM tomcat container with a bundled/shared process engine, you will see its job executor start up in the logs. 

However, if you continue to see this issue, please reopen or create a new issue here! Many thanks for your interest in the plugin - and apologies for my late answer!
