### ISSUE TITLE
Release date for version 0.5.0

### ISSUE THREAD

**Issue by richardgear** [plexiti/camunda-grails-plugin#49]
Hi Martin,

Any tentative date of the release? Especially the fix is required to resolve the compilation issue in grails 2.4 and above. Thanks in advance.

**Comment by Luxor** [comment]
+1

**Comment by martinschimak** [comment]
I will test some small things today and release it tomorrow. It will then come "bundled" with camunda BPM 7.3.0 by default. You can always configure to use a previous version in BuildConfig.groovy. Thank you guys very much for your interest in the plugin!
