### ISSUE TITLE
Question / Camunda over Grails 3 (3.0.8)

### ISSUE THREAD

**Issue by andhdo** [plexiti/camunda-grails-plugin#57]
How can I get a compatible camunda bpm plugin version with grails-3?

**Comment by martinschimak** [comment]
Hi @andhdo - thank you for your interest. Currently there is no Grails 3 plugin version available. But I am in the middle of the work for it. See #52.

**Comment by ofctech** [comment]
Hello @martinschimak, have you news about comunda for grails 3?

**Comment by nfahem** [comment]
Hello @martinschimak i would like to integrate your camunda plugin in my project. could you please give me any ETA for your grails 3 plugin release.
Kind regards

**Comment by acarrascosa** [comment]
hey! @martinschimak @ofctech @nfahem 
Any new updates about the issue?
